title: "Wenzhen Zhu Blog"
author: "Wenzhen Zhu"
description: "Let's get schwifty!" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
url: "http://zhuwenzhen.github.io"
email: "wenzhen@wustl.edu"
twitter_username: "wenzhen_zhu"
github_username: "zhuwenzhen"
linkedin_username: "wenzhenzhu"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
markdown: kramdown
permalink: pretty
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: "minima"

rss: rss
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
